// config.js — auto-generated by the UI
export default {
  baseURL: "https://books.toscrape.com",
  crawl: {
    maxPages: 30,
    maxDepth: 5,
    waitAfterAction: 500,
    seedPaths: []
  },
  auth: { type: "none" },
  output: {
    rawDir: "tests/generated/site-maps/raw",
    summaryFile: "tests/generated/site-maps/crawl-summary.json"
  }
};
